#!/usr/bin/env python

import os
import subprocess
import sys


def compile(file_name, problem_name, file_type):
    command = ""
    if file_type == "c":
        command = ' '.join(['gcc', file_name, '-o', problem_name])
    elif file_type == "cpp":
        command = ' '.join(['g++', file_name, '-o', problem_name])
    elif file_type == "java":
        command = ' '.join(['javac', file_name])
    else:
        command = ' '.join(['ruby', file_name])

    compile_status = ""
    try:
        compile_status = subprocess.check_output(command, shell=True)
    except subprocess.CalledProcessError:
        pass
    finally:
        return compile_status

argument = sys.argv[1]
if not os.path.isfile(argument):
    print "No such file!"
    sys.exit(1)

file_name_struct = argument.split(".")
problem_name = file_name_struct[0]
file_type = file_name_struct[-1]

supported_languages = ["c", "cpp", "py", "rb", "java"]
if file_type not in supported_languages:
    print "Language not supported"
    sys.exit(1)

print compile(argument, problem_name, file_type)
